language: node_js
node_js:
- 8.9
install:
- yarn install-all
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAJQA766P2RW32RWLA
  secret_access_key:
    secure: KMHkdXzKyndU41CcPM4JSbeyvhCGiG7a6Inm2p/Te762502rAQFpjdn8Nw2BoRjuitTLzYtmM4/+1gYn60idgXjf8EpG3OvHVh7io+Oz4C2tzEZiYW+5iiRGTBHHVWhIuBRIHi2Dz0OyPgGSBDMSt/6lbFh/B2SanHx97jDCOsIqdC93iAlxkJVH+MKijomRNAFh6gj5FkfmcLTb08rtBV5iNiktUrHnxWnyMHQbFuzzYrLWOZ8t16zr43FC858Je9NNrwidZslkEWHXSluPpGds9SOR4lAGHrnwaEyKdTJGclqK1nNANHbOEbmq9VxtCbLRheTrNsYPGLZfrbCGg42O+4UylKIMLrrIlUQEdQHstSMEXDTMSIEAsSWxWSMMAW5L9SlFRJ3Kj42LjvN7JOjL9UrHskrRY/rugaNzppck7VM1u/exSjVne3hxelUy43b6GjV52HUxGbupYxuf+Mf4oXjqCOHRzRvCCM+6c50JKyuJ2NmM9iCoWAloAm3QWoiR/1VZVXwWA57vhTRFqGxQsds4o2609mXSNuUvbFyew6pwMO+xYmuHSHGP1FDtfqo4lNlzOtQuxudY9ZP8IjASQocwIjeZEzCcwTTow+8UooTUYBg+pUl7iR4sTyOzIzutzdnItvPRr+yd4DLzHVSjDr4dFsKtqWzGVrq6KCY=
  bucket: pixelybets-app
  skip_cleanup: true
  local_dir: build
